version: '3.7'
services:
    php8-sf6:
        container_name: php8-sf6
        build: php8-sf6
        ports:
            - "8000:8000"
        volumes:
            - ./project:/var/www/html
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    database:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: password
            POSTGRES_USER: symfony
        volumes:
            - database_data:/var/lib/postgresql/data:rw
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
volumes:
    database_data: